---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kit-account
  namespace: kit-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kit-role
subjects:
  - kind: ServiceAccount
    name: kit-account
    namespace: kit-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
