apiVersion: apps/v1
kind: Deployment
metadata:
  name: kit
  namespace: kit-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kit
  template:
    metadata:
      labels:
        app: kit
    spec:
      serviceAccountName: kit-account
      initContainers:
        - name: init-pvc
          image: ghcr.io/lajosbencz/kit:latest
          command: ["sh", "-c", "if [ ! -f /kit.git.pvc/HEAD ]; then cp -r /kit.git /kit.git.pvc; fi"]
          volumeMounts:
            - name: kit-volume
              mountPath: /var/kit/kit.git.pvc
      containers:
        - name: kit
          image: ghcr.io/lajosbencz/kit:latest
          volumeMounts:
            - name: kit-volume
              mountPath: /kit.git
          ports:
            - containerPort: 22
      volumes:
        - name: kit-volume
          persistentVolumeClaim:
            claimName: kit-pvc
