apiVersion: apps/v1
kind: Deployment
metadata:
  name: kit
  namespace: kit-system
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: kit
  template:
    metadata:
      labels:
        app: kit
    spec:
      serviceAccountName: kit-account
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: init-pvc
          image: ghcr.io/lajosbencz/kit:latest
          command:
            - "sh"
            - "-c"
            - |
              if [ ! -f /var/kit/pvc.init/kit.git/HEAD ]; then
                git init --bare /var/kit/pvc.init/kit.git
                cp /var/kit/scripts/post-receive /var/kit/pvc.init/kit.git/hooks/
                chmod +x /var/kit/pvc.init/kit.git/hooks/post-receive
              fi
          volumeMounts:
            - name: kit-volume
              mountPath: /var/kit/pvc.init
      containers:
        - name: kit
          image: ghcr.io/lajosbencz/kit:latest
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
          volumeMounts:
            - name: kit-hostkeys
              mountPath: /var/kit/hostkeys/ssh_host_rsa_key
              mountPropagation: HostToContainer
              subPath: ssh_host_rsa_key
            - name: kit-hostkeys
              mountPath: /var/kit/hostkeys/ssh_host_ed25519_key
              mountPropagation: HostToContainer
              subPath: ssh_host_ed25519_key
            - name: kit-hostkeys
              mountPath: /var/kit/hostkeys/ssh_host_ecdsa_key
              mountPropagation: HostToContainer
              subPath: ssh_host_ecdsa_key
            - name: kit-authkeys
              mountPath: /var/kit/authkeys/authorized_keys
              mountPropagation: HostToContainer
              subPath: authorized_keys
            - name: kit-volume
              mountPath: /var/kit/pvc
              mountPropagation: HostToContainer
          ports:
            - containerPort: 2222
      volumes:
        - name: kit-volume
          persistentVolumeClaim:
            claimName: kit-pvc
        - name: kit-hostkeys
          secret:
            secretName: kit-hostkeys
            defaultMode: 384
        - name: kit-authkeys
          configMap:
            name: kit-authkeys
            defaultMode: 384
