apiVersion: apps/v1
kind: Deployment
metadata:
  name: kit
  namespace: kit-system
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: kit
  template:
    metadata:
      labels:
        app: kit
    spec:
      serviceAccountName: kit-account
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: init-pvc
          image: ghcr.io/lajosbencz/kit:latest
          command:
            - "sh"
            - "-c"
            - |
              if [ ! -f /var/kit/pvc.init/kit.git/HEAD ]; then
                git init --bare /var/kit/pvc.init/kit.git
                cp /var/kit/scripts/post-receive /var/kit/pvc.init/kit.git/hooks/
                chmod +x /var/kit/pvc.init/kit.git/hooks/post-receive
              fi
              chown -R git:git /var/kit/pvc.init
          volumeMounts:
            - name: kit-volume
              mountPath: /var/kit/pvc.init
      containers:
        - name: kit
          image: ghcr.io/lajosbencz/kit:latest
          securityContext:
            runAsUser: 1000
          volumeMounts:
            - name: kit-hostkeys
              mountPath: /var/kit/hostkeys
            - name: kit-authkeys
              mountPath: /var/kit/authkeys
            - name: kit-volume
              mountPath: /var/kit/pvc
          ports:
            - containerPort: 2222
      volumes:
        - name: kit-volume
          persistentVolumeClaim:
            claimName: kit-pvc
        - name: kit-hostkeys
          secret:
            secretName: kit-hostkeys
            items:
              - key: ssh_host_rsa_key
                path: ssh_host_rsa_key
                mode: 384
              - key: ssh_host_ed25519_key
                path: ssh_host_ed25519_key
                mode: 384
              - key: ssh_host_ecdsa_key
                path: ssh_host_ecdsa_key
                mode: 384
        - name: kit-authkeys
          configMap:
            name: kit-authkeys
            items:
              - key: authorized_keys
                path: authorized_keys
                mode: 384
