apiVersion: apps/v1
kind: Deployment
metadata:
  name: kit
  namespace: kit-system
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: kit
  template:
    metadata:
      labels:
        app: kit
    spec:
      serviceAccountName: kit-account
      initContainers:
        - name: init-pvc
          image: ghcr.io/lajosbencz/kit:latest
          command:
            - "sh"
            - "-c"
            - "if [ ! -f /var/kit/mount.init/kit.git/HEAD ]; then cp -r /var/kit/mount/kit.git /var/kit/mount.init/; chown -R git:git /var/kit/mount.init/kit.git; fi"
          volumeMounts:
            - name: kit-volume
              mountPath: /var/kit/mount.init
      containers:
        - name: kit
          image: ghcr.io/lajosbencz/kit:latest
          volumeMounts:
            - name: kit-volume
              mountPath: /var/kit/mount
          ports:
            - containerPort: 22
      volumes:
        - name: kit-volume
          persistentVolumeClaim:
            claimName: kit-pvc
