apiVersion: apps/v1
kind: Deployment
metadata:
  name: kit
  namespace: kit-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kit
  template:
    metadata:
      labels:
        app: kit
    spec:
      serviceAccountName: kit-account
      containers:
        - name: kit
          image: ghcr.io/lajosbencz/kit:latest
          ports:
            - containerPort: 22
