apiVersion: v1
kind: Service
metadata:
  name: kit
  namespace: kit-system
spec:
  type: ClusterIP
#  clusterIP: None
  selector:
    app: kit
  ports:
    - name: sshd
      port: 22
      protocol: TCP
      targetPort: 2222
